### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by kungfooman** [Port-Able/Port-Able-Suite#1]
Hi, this looks really interesting, but where is the setup exe?

**Comment by koryboc** [comment]
Hi,

visit https://github.com/Port-Able/Port-Able-Suite/releases/latest to download
the `Binaries_self-extract.exe` file and follow the instructions, after
extracting you only need to run `AppsLauncher.exe`, enjoy! :relaxed:

Regards,
Roy
