### ISSUE TITLE
User rights escalation for Update process

### ISSUE THREAD

**Issue by kungfooman** [Port-Able/Port-Able-Suite#2]
Hi, I am on Windows 10 and using Guest user accounts with Port-Able-Suite apps, so all the utils like Gyazo etc. don't run with full admin rights. I consider each Guest account to be compromised by nature, so in those Guest instances I don't allow anything to escalate rights to Admin level (my kung account in picture).

But the updater - for whatever reasons - wants to escalate:

![rights escalation](https://user-images.githubusercontent.com/5236548/44183208-789b7900-a10a-11e8-9d16-74705ec9708f.jpg)

The content:

```BAT
@echo off
title "e2e61e4d-e5f3-4797-9c18-68e29d398a93"

taskkill /f /im "AppsDownloader.exe" >nul 2>&1
taskkill /f /im "AppsDownloader64.exe" >nul 2>&1
taskkill /f /im "AppsLauncher.exe" >nul 2>&1
taskkill /f /im "AppsLauncher64.exe" >nul 2>&1

cd /d "%~dp0"
7zG.exe x Update.7z -o"C:\Users\discord\Desktop\Port-Able\" -y
ping localhost -n 5 >nul
del /f /q Update.7z
del /f /q 7z.dll
del /f /q 7zG.exe

set path=%WinDir%\System32\cmd.exe
if exist %0 start "790dedb7-1e3c-47e1-b3f7-356c9432a763" %path% /c del /f /q %0 && taskkill /fi "e2e61e4d-e5f3-4797-9c18-68e29d398a93" /im cmd.exe /t
exit /b
```

I don't see anything which would need System rights for these basic file operations.

**Comment by koryboc** [comment]
Hi,

this process is started with elevated privileges to guarantee success even in the worst case scenario.
You should know that replacing potentially used files are critical **basic operations** on Windows.

Anyway, I'll take care of it for an upcoming release! 😉
But please keep in mind that you'll have to update this way once. :stuck_out_tongue_winking_eye:

Regards,
Roy

**Comment by koryboc** [comment]
Solved for upcoming release: https://github.com/Port-Able/Port-Able-Suite/commit/6334beeda2dc09db2f915792dfb79c5d04d30d27 😉
