### ISSUE TITLE
Battle.net issue

### ISSUE THREAD

**Issue by localhost127001** [Port-Able/Port-Able-Suite#5]
### Expected behavior
Games tab should list all games installed  instead we got Ooops! an error occurred while loading game information

### Desktop (please complete the following information):
 - OS: Windows 10 Pro
 - Version 1909

### Prerequisites

* [x] Can you reproduce the problem? every time
* [x] Are you running the latest version? Yes(your version ofc), I've tried updating battle.net files manually, still no dice

**Comment by koryboc** [comment]
Hello @localhost127001,

thanks for your report and sorry for the late reply, I rarely check emails and notifications on weekends and holidays.

I tried to reproduce your problem but I couldn't, it works fine for me...

Please checkout your `.\BattleNetPortable\App\Battle.net` folder, there should be just a single folder called like `Battle.net.11943` and two files called `Battle.net Launcher.exe` and `Battle.net.exe`, if you have more than that it could be the case that something happened wrong when updating. So you should keep a single `Battle.net.11943` folder with the largest number and the two execution files mentioned above.

I would be happy if you could give me a short feedback if this could solve your problem. Then I could find a solution for an upcoming release so it doesn't happen again. 😉

See you later 👋

**Comment by localhost127001** [comment]
I have sinned myself for not keeping update of my own thread
But it has since been solved by adding manually Battle.net agent service to the environment
Not sure how or why but it's working now

**Comment by koryboc** [comment]
Thanks for your feedback.

The agent is of course very important for Battle.net. I wonder rather why it wasn't automatically added to the environment. Battle.net should normally do this on its own. 🤔 

Thanks again, see ya! 😉
